### ISSUE TITLE
Wrong configuration name in BearerStrategy

### ISSUE THREAD

**Issue by flexwie** [TypedProject/tsed-example-passport-azure-ad#2]
I am trying to setup passport with an Azure AD but am having some issues with it:

It seems that the setting we `get()` in the `BearerStrategy` has the wrong name (is: azureBearerOptions, should be: azure-bearer). When I change that, I get an Injection Error `TypeError: Passport.use is not a function` refering to the `Passport.use()` in line 54 of the BearerStrategy. 

Any idea why this isn't working?

**Comment by Romakita** [comment]
Hello @flexwie 
The example is not up to date. I think, you have to change the passport import. 

Remove the ˋ*` by default import.

see you
Romain

**Comment by flexwie** [comment]
Thanks for your help @Romakita ! That solved it for me!
